language: go

go:
 - "1.12"

install:
 - env GO111MODULE=on go mod download

script:
 - make test
 - diff <(go run "golang.org/x/tools/cmd/goimports" -d .) <(printf "")
 - diff <(golint ./...) <(printf "")